services:
  - type: web
    name: flowise-chat-embed-static
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
